name: login_firebase_complete
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  liquid_swipe: ^3.1.0
  get: ^4.6.6
  smooth_page_indicator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/logo/burger.jpg
  image_dark: assets/logo/burger.jpg

  android_12:
    image: assets/logo/burger.jpg
    icon_background_color: "#f7f6f1"
    image_dark: assets/logo/burger.jpg
    icon_background_color_dark: "#272727"


flutter:

  uses-material-design: true

  
  assets:
     - assets/images/
     - assets/images/on_boarding_images/
     - assets/logo/


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
